services:
  backend:
    image: ghcr.io/realamirhdr/bloodborne-ai/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/data/chroma:/app/data/chroma
    restart: unless-stopped

  frontend:
    image: ghcr.io/realamirhdr/bloodborne-ai/frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
